# Generated by Django 5.2.10 on 2026-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_sequential_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comprapadre',
            name='numero',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='canal_venta',
            field=models.CharField(choices=[('local', 'Local'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('telefono', 'Teléfono'), ('otro', 'Otro')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('factura', 'Factura'), ('debito', 'Debito'), ('credito', 'Crédito')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
