# Generated by Django 5.2.10 on 2026-03-06 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_compra_numero_alter_comprapadre_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
