# Generated by Django 5.2.10 on 2026-05-08 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_producto_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
