# Generated by Django 5.2 on 2026-05-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_producto_id_producto_unique_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprapadre',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
