# Generated by Django 5.2.10 on 2026-06-25 07:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_venta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprapadre',
            name='factura',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='facturas/'),
        ),
    ]
