# Generated by Django 5.2 on 2026-07-09 03:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_comprapadre_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True)),
                ('origen_model', models.CharField(blank=True, default='', max_length=50)),
                ('origen_id', models.IntegerField(blank=True, null=True)),
                ('es_manual', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_financieros', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_distribucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('user', 'nombre'), name='unique_categoria_distribucion_por_usuario')],
            },
        ),
    ]
