# Generated by Django 5.2 on 2026-07-11 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_movimientofinanciero_categoriadistribucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='canal_venta',
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cuenta_rut', 'Cuenta Rut'), ('mercado_pago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pendiente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
